### ISSUE TITLE
FE Create New User

### ISSUE THREAD

**Issue by reidsmiller** [ithill22/draft_madness_fe#1]
As a visitor, when I visit the welcome page, I see a button to Sign Up.
When I click the Sign Up button, I am taken to the New User page.

When I fill out all fields with valid information and click Submit, I am taken to my user dashboard page.

**Comment by KatieLonsdale** [comment]
As a visitor, when I visit the welcome page:
I see a button to Sign Up
When I click the Sign Up button,
I am taken to the New User page.
